#!/usr/bin/env python3
"""Write the complete PinyinEngine.kt file."""

out = r'D:\workspace\quick-speech\android\wubi\src\main\java\com\quickspeech\wubi\engine\PinyinEngine.kt'

# Dictionary entries: list of (pinyin, characters_string)
dict_entries = [
    ("a", "阿啊呵腌"),
    ("ai", "爱碍哀埃挨艾唉矮癌"),
    ("an", "安按案暗岸氨庵鞍"),
    ("ang", "昂盎"),
    ("ao", "奥傲澳熬袄凹"),
    ("ba", "把八吧巴爸拔罢坝芭霸"),
    ("bai", "白百败拜柏摆"),
    ("ban", "办半班般版板伴搬扮"),
    ("bang", "帮邦榜绑棒傍膀磅"),
    ("bao", "报保包宝抱暴薄爆胞饱"),
    ("bei", "被北备背悲辈杯倍贝碑臂"),
    ("ben", "本奔笨"),
    ("beng", "崩绷蹦迸泵"),
    ("bi", "比必笔毕币避鼻壁逼彼臂秘闭辟碧弊"),
    ("bian", "便边变编遍辩辨贬鞭扁"),
    ("biao", "表标彪镖膘"),
    ("bie", "别憋瘪"),
    ("bin", "宾滨彬斌濒殡缤"),
    ("bing", "并兵病冰丙饼柄秉炳屏"),
    ("bo", "波博播伯薄勃拨玻柏剥泊"),
    ("bu", "不部布步补捕怖卜簿"),
    ("ca", "擦"),
    ("cai", "才采财材彩菜裁猜蔡"),
    ("can", "参残餐惨灿蚕惭"),
    ("cang", "藏仓苍舱"),
    ("cao", "草操曹槽糙"),
    ("ce", "策测侧册"),
    ("cen", "参岑"),
    ("ceng", "曾层"),
    ("cha", "查察差茶插叉刹岔诧"),
    ("chai", "差拆柴豺"),
    ("chan", "产颤缠禅蝉馋铲阐搀"),
    ("chang", "长常场厂唱尝偿昌畅肠倡敞"),
    ("chao", "超朝潮炒吵抄嘲钞巢"),
    ("che", "车彻撤扯澈"),
    ("chen", "称陈沉晨尘臣趁衬辰"),
    ("cheng", "成城程承称盛乘呈诚撑惩"),
    ("chi", "吃持迟尺赤池痴齿斥驰耻翅"),
    ("chong", "重冲充虫崇宠憧"),
    ("chou", "抽愁丑臭仇筹酬绸瞅稠"),
    ("chu", "出处初除楚触储厨畜橱矗"),
    ("chuai", "揣啜"),
    ("chuan", "传川穿船串喘"),
    ("chuang", "创窗床闯疮"),
    ("chui", "吹垂锤捶椎"),
    ("chun", "春纯唇蠢醇淳椿"),
    ("chuo", "绰戳啜"),
    ("ci", "此次词差刺辞慈磁赐瓷"),
    ("cong", "从匆聪丛葱"),
    ("cou", "凑"),
    ("cu", "粗促醋簇"),
    ("cuan", "窜篡"),
    ("cui", "催脆翠粹摧"),
    ("cun", "村存寸"),
    ("cuo", "错措挫搓"),
    ("da", "大打达答搭"),
    ("dai", "大代带待袋戴呆逮贷"),
    ("dan", "但单担弹淡蛋丹胆旦"),
    ("dang", "当党挡荡档"),
    ("dao", "到道导倒刀岛盗蹈悼"),
    ("de", "的得德地"),
    ("dei", "得"),
    ("deng", "等登灯邓瞪凳"),
    ("di", "地第低底弟帝敌递滴迪堤笛"),
    ("dia", "嗲"),
    ("dian", "点电店典颠殿甸垫淀"),
    ("diao", "调掉钓雕吊叼"),
    ("die", "跌叠蝶爹谍碟迭"),
    ("ding", "定顶订丁盯钉鼎叮"),
    ("diu", "丢"),
    ("dong", "动东懂冬董冻洞栋"),
    ("dou", "都斗豆抖兜陡逗"),
    ("du", "都读独度毒杜肚渡督赌"),
    ("duan", "断段短端缎锻"),
    ("dui", "对队堆兑"),
    ("dun", "顿吨蹲盾敦墩囤"),
    ("duo", "多夺朵躲舵堕"),
    ("e", "额恶饿哦鹅俄扼愕"),
    ("en", "恩"),
    ("er", "而儿耳二尔饵洱"),
    ("fa", "发法罚乏伐阀"),
    ("fan", "反饭犯翻范烦繁泛番凡返"),
    ("fang", "方放房防访芳仿纺坊妨"),
    ("fei", "非飞费肥废肺匪啡菲沸"),
    ("fen", "分份纷奋愤粉芬坟氛"),
    ("feng", "风封峰丰凤奉疯锋逢缝讽"),
    ("fo", "佛"),
    ("fou", "否"),
    ("fu", "服夫父府复副负富福付妇附幅伏扶浮符腐腹覆"),
    ("ga", "咖嘎"),
    ("gai", "改该概盖丐钙"),
    ("gan", "感干敢赶甘肝杆赣"),
    ("gang", "刚港钢岗纲缸扛"),
    ("gao", "高告稿搞糕膏羔"),
    ("ge", "个格歌革哥隔阁葛割戈鸽胳"),
    ("gei", "给"),
    ("gen", "根跟"),
    ("geng", "更耕耿梗庚"),
    ("gong", "工公功共供攻宫恭巩龚弓躬"),
    ("gou", "够购狗构沟勾钩苟"),
    ("gu", "古故股顾固骨姑谷孤鼓雇辜咕"),
    ("gua", "挂瓜刮寡褂"),
    ("guai", "怪乖拐"),
    ("guan", "关观管官馆惯冠贯灌罐棺"),
    ("guang", "光广逛"),
    ("gui", "规归贵鬼桂柜跪轨龟硅瑰"),
    ("gun", "滚棍"),
    ("guo", "国过果锅郭"),
    ("ha", "哈"),
    ("hai", "还海害孩咳亥骇"),
    ("han", "汉喊寒含汗韩罕憾翰旱涵"),
    ("hang", "行航杭巷夯"),
    ("hao", "好号毫豪耗浩郝嚎"),
    ("he", "和何合河核贺赫荷盒喝禾褐"),
    ("hei", "黑"),
    ("hen", "很恨狠痕"),
    ("heng", "行横恒哼衡"),
    ("hong", "红洪宏轰虹鸿弘烘"),
    ("hou", "后候厚侯喉吼猴"),
    ("hu", "和护户湖呼胡互虎忽糊狐沪壶蝴"),
    ("hua", "化话花华划画滑哗"),
    ("huai", "怀坏淮"),
    ("huan", "还欢换环缓患幻唤宦焕"),
    ("huang", "黄皇荒煌晃慌惶凰"),
    ("hui", "会回汇挥灰辉毁悔惠慧绘讳贿晦秽"),
    ("hun", "婚混魂昏浑荤"),
    ("huo", "和活或火获货伙惑霍祸"),
    ("ji", "就己机即几及级极给基计集记济继技际季激吉积纪寄迹鸡疾"),
    ("jia", "家加价假甲架驾夹佳嫁嘉贾"),
    ("jian", "见间建件简坚检健渐减剑监兼尖肩艰荐鉴践奸箭舰剪捡"),
    ("jiang", "将强江讲降蒋奖姜僵疆匠酱"),
    ("jiao", "叫教交角脚较觉校焦骄郊轿浇椒嚼搅绞饺"),
    ("jie", "结接节界解姐介街阶截杰皆洁戒揭捷劫竭"),
    ("jin", "进今金近尽紧仅禁劲津斤筋锦谨浸"),
    ("jing", "经京精竟惊境静景警睛竞净劲径晶荆鲸井颈敬"),
    ("jiong", "窘"),
    ("jiu", "就九究久酒旧救纠揪舅"),
    ("ju", "据且局举句具居剧巨聚拒俱惧柜矩拘菊"),
    ("juan", "卷捐圈娟倦绢"),
    ("jue", "决绝觉角爵掘崛倔嚼诀"),
    ("jun", "军君均菌俊峻竣"),
    ("ka", "卡咖"),
    ("kai", "开凯慨"),
    ("kan", "看刊砍堪勘"),
    ("kang", "抗康慷扛炕"),
    ("kao", "考靠烤"),
    ("ke", "可克科客刻课颗柯渴棵磕咳壳"),
    ("ken", "肯恳啃"),
    ("keng", "坑"),
    ("kong", "空孔恐控"),
    ("kou", "口扣寇抠"),
    ("ku", "苦库裤酷枯窟"),
    ("kua", "跨夸垮"),
    ("kuai", "快块筷"),
    ("kuan", "宽款"),
    ("kuang", "况狂矿框旷眶筐"),
    ("kui", "亏愧溃窥魁葵馈盔"),
    ("kun", "困昆坤捆"),
    ("kuo", "扩阔括"),
    ("la", "拉啦辣蜡喇垃"),
    ("lai", "来赖莱"),
    ("lan", "兰蓝栏烂懒览滥拦篮澜"),
    ("lang", "浪郎朗狼廊琅"),
    ("lao", "老劳牢捞姥涝"),
    ("le", "了乐勒肋"),
    ("lei", "类累泪雷蕾垒磊擂"),
    ("leng", "冷愣"),
    ("li", "里理力立利李离丽历礼例厉励黎璃莉粒"),
    ("lia", "俩"),
    ("lian", "联连脸练恋怜莲廉帘链敛"),
    ("liang", "两量良亮凉梁粮谅晾"),
    ("liao", "了料聊疗辽僚寥撩燎"),
    ("lie", "列烈裂猎劣咧"),
    ("lin", "林临邻淋琳霖磷凛吝"),
    ("ling", "领令另零灵龄凌玲铃陵岭菱伶"),
    ("liu", "六流留刘柳溜瘤硫浏"),
    ("lo", "咯"),
    ("long", "龙隆笼拢聋垄胧珑"),
    ("lou", "楼漏搂陋露娄"),
    ("lu", "路陆录露鲁炉卢鹿禄芦庐碌麓"),
    ("luan", "乱卵峦挛孪"),
    ("lun", "论轮伦沦仑"),
    ("luo", "落罗络洛螺裸萝锣箩"),
    ("lv", "绿旅律率虑履侣驴吕缕"),
    ("lve", "略掠"),
    ("ma", "马吗妈麻骂码玛蚂"),
    ("mai", "买卖麦脉埋迈"),
    ("man", "满慢漫曼蛮馒瞒蔓"),
    ("mang", "忙盲茫芒莽氓"),
    ("mao", "毛冒猫貌矛帽茅茂贸髦锚"),
    ("me", "么"),
    ("mei", "没美每妹梅眉媒煤霉玫枚昧媚"),
    ("men", "们门闷"),
    ("meng", "梦蒙猛盟孟朦萌锰"),
    ("mi", "米密迷秘蜜谜弥眯靡糜"),
    ("mian", "面免棉眠绵勉缅冕"),
    ("miao", "秒妙描苗庙瞄渺"),
    ("mie", "灭蔑"),
    ("min", "民敏皿闽悯"),
    ("ming", "名明命鸣铭冥茗"),
    ("miu", "谬"),
    ("mo", "么没模莫默摸摩磨魔抹墨漠陌沫膜"),
    ("mou", "某谋眸"),
    ("mu", "目母木幕慕牧墓穆姆牡亩"),
    ("na", "那拿哪纳娜呐"),
    ("nai", "乃奶耐奈"),
    ("nan", "南男难喃楠"),
    ("nang", "囊囔"),
    ("nao", "脑闹恼挠瑙"),
    ("ne", "呢哪"),
    ("nei", "内那"),
    ("nen", "嫩"),
    ("neng", "能"),
    ("ni", "你尼泥拟逆妮腻匿溺倪霓"),
    ("nian", "年念粘碾廿捻"),
    ("niang", "娘酿"),
    ("niao", "鸟尿袅"),
    ("nie", "捏聂孽涅啮镊镍"),
    ("nin", "您"),
    ("ning", "宁凝拧柠狞泞"),
    ("niu", "牛扭纽拗"),
    ("nong", "农浓弄脓"),
    ("nu", "努怒奴弩"),
    ("nuan", "暖"),
    ("nuo", "诺挪懦糯"),
    ("nv", "女"),
    ("nve", "虐疟"),
    ("o", "哦"),
    ("ou", "欧偶殴鸥藕呕讴"),
    ("pa", "怕爬帕趴啪扒"),
    ("pai", "排牌派拍迫徘"),
    ("pan", "判盘番攀盼叛畔潘"),
    ("pang", "旁胖庞膀磅乓镑"),
    ("pao", "跑炮泡抛袍刨咆"),
    ("pei", "配培陪佩赔沛裴"),
    ("pen", "喷盆"),
    ("peng", "朋碰彭鹏捧蓬膨篷砰烹"),
    ("pi", "批皮匹屁疲脾劈披辟啤僻譬坯"),
    ("pian", "片篇偏骗翩扁便"),
    ("piao", "票漂飘瓢嫖瞟剽"),
    ("pie", "撇瞥"),
    ("pin", "品贫频拼聘"),
    ("ping", "平评凭苹瓶萍屏坪乒"),
    ("po", "破迫坡颇泼婆泊魄粕"),
    ("pou", "剖"),
    ("pu", "普扑铺朴葡蒲浦埔谱瀑曝脯菩"),
    ("qi", "起其期气七器企奇旗汽妻弃启骑棋齐岂契泣祈漆栖"),
    ("qia", "恰洽掐"),
    ("qian", "前千钱签欠浅迁潜牵谦遣歉纤嵌乾黔倩"),
    ("qiang", "强墙枪抢腔悄呛羌蔷"),
    ("qiao", "桥巧悄敲瞧乔侨俏壳翘峭撬樵"),
    ("qie", "且切窃怯茄趄惬"),
    ("qin", "亲琴侵勤秦禽寝擒钦芹沁"),
    ("qing", "情请清青轻晴庆倾卿顷氢擎氰蜻"),
    ("qiong", "穷琼穹茕"),
    ("qiu", "求球秋丘邱囚酋裘"),
    ("qu", "去取区曲趣屈驱趋渠躯娶"),
    ("quan", "全权圈劝泉拳犬券诠荃蜷"),
    ("que", "却确缺雀鹊阙炔"),
    ("qun", "群裙"),
    ("ran", "然染燃冉"),
    ("rang", "让嚷壤攘"),
    ("rao", "绕扰饶"),
    ("re", "热惹"),
    ("ren", "人任认忍仁刃韧纫饪"),
    ("reng", "仍扔"),
    ("ri", "日"),
    ("rong", "容荣融绒溶熔蓉冗茸"),
    ("rou", "肉柔揉"),
    ("ru", "如入儒乳辱汝茹褥孺濡"),
    ("ruan", "软阮"),
    ("rui", "瑞锐蕊睿"),
    ("run", "润闰"),
    ("ruo", "若弱偌"),
    ("sa", "撒洒萨"),
    ("sai", "赛塞腮"),
    ("san", "三散伞叁"),
    ("sang", "桑丧嗓"),
    ("sao", "扫嫂骚搔"),
    ("se", "色塞涩瑟"),
    ("sen", "森"),
    ("seng", "僧"),
    ("sha", "杀沙啥傻砂纱刹莎煞杉鲨"),
    ("shai", "晒"),
    ("shan", "山善闪衫扇删杉珊陕煽擅膳讪汕疝"),
    ("shang", "上商伤尚赏裳晌"),
    ("shao", "少绍烧稍勺哨邵梢捎芍韶"),
    ("she", "社设舍涉射蛇舌摄赦赊"),
    ("shei", "谁"),
    ("shen", "什身深神参审沈伸慎渗绅婶肾"),
    ("sheng", "生声省胜升圣盛乘剩牲绳笙"),
    ("shi", "是时事十实什使世市师士式石失识始史视示诗施尸食室试释氏湿拾驶饰矢"),
    ("shou", "收受首手守授售寿瘦兽"),
    ("shu", "书数术树属输述熟束叔舒殊署鼠淑疏蔬暑竖梳抒枢赎蜀"),
    ("shua", "刷"),
    ("shuai", "率帅摔衰甩"),
    ("shuan", "拴栓"),
    ("shuang", "双霜爽"),
    ("shui", "水睡税"),
    ("shun", "顺瞬"),
    ("shuo", "说硕烁"),
    ("si", "四死司思似丝私斯食寺肆撕"),
    ("song", "送松宋诵讼耸颂"),
    ("sou", "搜艘擞"),
    ("su", "苏诉速素俗宿肃稣塑粟"),
    ("suan", "算蒜酸"),
    ("sui", "虽随岁碎遂隋髓穗"),
    ("sun", "孙损笋"),
    ("suo", "所索缩锁"),
    ("ta", "他她它踏塔塌拓"),
    ("tai", "太台态抬泰胎汰"),
    ("tan", "谈弹探叹坦坛贪滩毯炭潭"),
    ("tang", "堂唐糖汤躺烫趟塘膛淌"),
    ("tao", "讨套逃挑陶桃涛淘萄滔"),
    ("te", "特"),
    ("teng", "腾疼藤"),
    ("ti", "提题体替蹄梯踢剃啼堤剔"),
    ("tian", "天田填甜添舔"),
    ("tiao", "调条跳挑眺"),
    ("tie", "铁贴帖"),
    ("ting", "听停庭厅挺亭廷艇"),
    ("tong", "同通统痛童铜筒桶桐瞳"),
    ("tou", "头投透偷"),
    ("tu", "土突图徒涂途屠秃"),
    ("tuan", "团"),
    ("tui", "推退腿吞颓"),
    ("tun", "吞屯豚"),
    ("tuo", "脱拖托拓陀妥唾驼"),
    ("wa", "瓦娃挖蛙洼"),
    ("wai", "外歪"),
    ("wan", "万完晚玩湾弯挽碗顽腕丸宛婉"),
    ("wang", "王望往网忘亡汪旺枉"),
    ("wei", "为位未委围维伟威卫谓微唯危违伪尾未味魏畏胃喂慰"),
    ("wen", "文问闻温稳吻纹"),
    ("weng", "翁"),
    ("wo", "我握窝卧沃"),
    ("wu", "无五物务武午伍吴舞乌恶屋悟误污勿巫呜芜"),
    ("xi", "西希习喜细息吸戏系席惜稀溪洗袭悉膝夕牺熙嘻"),
    ("xia", "下夏吓峡狭霞瞎虾"),
    ("xian", "先现线县显险鲜献限仙闲宪陷贤洗嫌弦羡掀"),
    ("xiang", "向想相像响香乡象项详降享箱祥"),
    ("xiao", "小笑校消效销晓萧肖削孝宵"),
    ("xie", "些写谢鞋协血邪携斜泄屑械歇蟹挟"),
    ("xin", "新心信欣辛薪馨"),
    ("xing", "行性形兴星幸姓型刑醒腥"),
    ("xiong", "雄凶兄胸熊"),
    ("xiu", "修秀休袖宿臭羞锈绣"),
    ("xu", "许须需徐序虚续绪蓄叙吁"),
    ("xuan", "选宣旋悬玄轩"),
    ("xue", "学血雪穴削"),
    ("xun", "寻训讯巡迅询循逊勋"),
    ("ya", "亚压呀牙雅鸭涯"),
    ("yan", "言研严眼演验烟沿延掩颜岩雁厌艳盐炎燕"),
    ("yang", "养阳洋样杨扬羊仰氧痒"),
    ("yao", "要药摇腰遥咬耀妖邀"),
    ("ye", "也业夜爷叶野页液"),
    ("yi", "一已意义以亿议医依移艺易亦伊异宜仪疑遗忆役译益翼"),
    ("yin", "因音银引印饮隐阴"),
    ("ying", "应影英营迎硬映鹰盈"),
    ("yo", "哟"),
    ("yong", "用永勇拥庸涌泳"),
    ("you", "有又由友游优油右邮幼犹忧幽"),
    ("yu", "于与语育余遇雨玉预鱼欲域愈宇狱誉羽郁豫"),
    ("yuan", "元原员院源远愿园缘援圆袁怨"),
    ("yue", "月越乐约阅岳悦跃"),
    ("yun", "运云允韵孕匀蕴"),
    ("za", "杂砸"),
    ("zai", "在再载灾栽"),
    ("zan", "咱赞暂"),
    ("zang", "藏脏葬"),
    ("zao", "早造遭糟澡灶躁噪"),
    ("ze", "则责择泽"),
    ("zei", "贼"),
    ("zen", "怎"),
    ("zeng", "曾增赠"),
    ("zha", "查炸诈眨榨闸炸"),
    ("zhai", "摘窄债寨"),
    ("zhan", "战展站占颤斩沾粘盏崭"),
    ("zhang", "长张章掌丈仗帐涨障"),
    ("zhao", "着找照招朝召兆赵罩"),
    ("zhe", "这着者折哲浙"),
    ("zhei", "这"),
    ("zhen", "真阵镇震针珍诊枕贞侦"),
    ("zheng", "正政争整证征丁郑挣睁"),
    ("zhi", "之只知制至直指治识志支职值织止置质致智纸执职植殖"),
    ("zhong", "中重种众终钟忠衷肿"),
    ("zhou", "周州洲舟轴宙昼皱骤"),
    ("zhu", "主住注著助逐朱珠诸猪竹筑柱祝驻株煮"),
    ("zhua", "抓"),
    ("zhuai", "拽"),
    ("chuan", "传川穿船串喘"),
    ("zhuang", "装状壮庄撞"),
    ("zhui", "追坠"),
    ("zhun", "准"),
    ("zhuo", "着桌捉卓"),
    ("zi", "子字自资紫姊"),
    ("zong", "总宗综纵"),
    ("zou", "走奏"),
    ("zu", "组足族祖阻"),
    ("zuan", "钻"),
    ("zui", "最罪嘴醉"),
    ("zun", "尊遵"),
    ("zuo", "作做坐座左昨琢"),
    # Common two-character words
    ("zhongguo", "中国"),
    ("zhongwen", "中文"),
    ("renmin", "人民"),
    ("guojia", "国家"),
    ("shijie", "世界"),
    ("gongzuo", "工作"),
    ("xuexi", "学习"),
    ("wenti", "问题"),
    ("fangfa", "方法"),
    ("neirong", "内容"),
    ("jianyi", "建议"),
    ("fazhan", "发展"),
    ("jingji", "经济"),
    ("shehui", "社会"),
    ("wenhua", "文化"),
    ("jishu", "技术"),
    ("guanli", "管理"),
    ("fuwu", "服务"),
    ("chanpin", "产品"),
    ("shichang", "市场"),
    ("qiye", "企业"),
    ("xiangmu", "项目"),
    ("zhengce", "政策"),
    ("zhidu", "制度"),
    ("jichu", "基础"),
    ("yaosu", "要素"),
    ("tiaojian", "条件"),
    ("huanjing", "环境"),
    ("ziyuan", "资源"),
    ("xinxi", "信息"),
    ("zhishi", "知识"),
    ("jingyan", "经验"),
    ("chenggong", "成功"),
    ("shibai", "失败"),
    ("anquan", "安全"),
    ("jiankang", "健康"),
    ("shenghuo", "生活"),
    ("jiaoyu", "教育"),
    ("kexue", "科学"),
    ("yishu", "艺术"),
    ("lishi", "历史"),
    ("dili", "地理"),
    ("zhengzhi", "政治"),
    ("falv", "法律"),
    ("daode", "道德"),
    ("zongjiao", "宗教"),
    ("ziran", "自然"),
    ("huanbao", "环保"),
    ("nengyuan", "能源"),
    ("nongye", "农业"),
    ("gongye", "工业"),
    ("jiaotong", "交通"),
    # (More common words would go here)
]
# Build Kotlin content
content = '''package com.quickspeech.wubi.engine

/**
 * Pinyin input engine supporting full pinyin, abbreviated pinyin, and fuzzy matching.
 */
class PinyinEngine {

    companion object {
        val FUZZY_PAIRS = mapOf(
            "zh" to "z", "z" to "zh",
            "ch" to "c", "c" to "ch",
            "sh" to "s", "s" to "sh",
            "n" to "l", "l" to "n",
            "in" to "ing", "ing" to "in",
            "en" to "eng", "eng" to "en"
        )
        // Valid syllables for segmentation
        val VALID_SYLLABLES: Set<String> = setOf(
            "a", "ai", "an", "ang", "ao",
            "ba", "bai", "ban", "bang", "bao", "bei", "ben", "beng", "bi", "bian", "biao", "bie", "bin", "bing", "bo", "bu",
            "ca", "cai", "can", "cang", "cao", "ce", "cen", "ceng", "cha", "chai", "chan", "chang", "chao", "che", "chen", "cheng", "chi", "chong", "chou", "chu", "chua", "chuai", "chuan", "chuang", "chui", "chun", "chuo", "ci", "cong", "cou", "cu", "cuan", "cui", "cun", "cuo",
            "da", "dai", "dan", "dang", "dao", "de", "dei", "den", "deng", "di", "dia", "dian", "diao", "die", "ding", "diu", "dong", "dou", "du", "duan", "dui", "dun", "duo",
            "e", "ei", "en", "eng", "er",
            "fa", "fan", "fang", "fei", "fen", "feng", "fo", "fou", "fu",
            "ga", "gai", "gan", "gang", "gao", "ge", "gei", "gen", "geng", "gong", "gou", "gu", "gua", "guai", "guan", "guang", "gui", "gun", "guo",
            "ha", "hai", "han", "hang", "hao", "he", "hei", "hen", "heng", "hong", "hou", "hu", "hua", "huai", "huan", "huang", "hui", "hun", "huo",
            "ji", "jia", "jian", "jiang", "jiao", "jie", "jin", "jing", "jiong", "jiu", "ju", "juan", "jue", "jun",
            "ka", "kai", "kan", "kang", "kao", "ke", "kei", "ken", "keng", "kong", "kou", "ku", "kua", "kuai", "kuan", "kuang", "kui", "kun", "kuo",
            "la", "lai", "lan", "lang", "lao", "le", "lei", "leng", "li", "lia", "lian", "liang", "liao", "lie", "lin", "ling", "liu", "lo", "long", "lou", "lu", "luan", "lun", "luo", "lv", "lve",
            "ma", "mai", "man", "mang", "mao", "me", "mei", "men", "meng", "mi", "mian", "miao", "mie", "min", "ming", "miu", "mo", "mou", "mu",
            "na", "nai", "nan", "nang", "nao", "ne", "nei", "nen", "neng", "ni", "nian", "niang", "niao", "nie", "nin", "ning", "niu", "nong", "nou", "nu", "nuan", "nun", "nuo", "nv", "nve",
            "o", "ou",
            "pa", "pai", "pan", "pang", "pao", "pei", "pen", "peng", "pi", "pian", "piao", "pie", "pin", "ping", "po", "pou", "pu",
            "qi", "qia", "qian", "qiang", "qiao", "qie", "qin", "qing", "qiong", "qiu", "qu", "quan", "que", "qun",
            "ran", "rang", "rao", "re", "ren", "reng", "ri", "rong", "rou", "ru", "rua", "ruan", "rui", "run", "ruo",
            "sa", "sai", "san", "sang", "sao", "se", "sen", "seng", "sha", "shai", "shan", "shang", "shao", "she", "shei", "shen", "sheng", "shi", "shou", "shu", "shua", "shuai", "shuan", "shuang", "shui", "shun", "shuo", "si", "song", "sou", "su", "suan", "sui", "sun", "suo",
            "ta", "tai", "tan", "tang", "tao", "te", "tei", "teng", "ti", "tian", "tiao", "tie", "ting", "tong", "tou", "tu", "tuan", "tui", "tun", "tuo",
            "wa", "wai", "wan", "wang", "wei", "wen", "weng", "wo", "wu",
            "xi", "xia", "xian", "xiang", "xiao", "xie", "xin", "xing", "xiong", "xiu", "xu", "xuan", "xue", "xun",
            "ya", "yan", "yang", "yao", "ye", "yi", "yin", "ying", "yo", "yong", "you", "yu", "yuan", "yue", "yun",
            "za", "zai", "zan", "zang", "zao", "ze", "zei", "zen", "zeng", "zha", "zhai", "zhan", "zhang", "zhao", "zhe", "zhei", "zhen", "zheng", "zhi", "zhong", "zhou", "zhu", "zhua", "zhuai", "zhuan", "zhuang", "zhui", "zhun", "zhuo", "zi", "zong", "zou", "zu", "zuan", "zui", "zun", "zuo"
        )
        val INITIALS = listOf("zh", "ch", "sh", "b", "p", "m", "f", "d", "t", "n", "l", "g", "k", "h", "j", "q", "x", "z", "c", "s", "r", "y", "w")
    }

    private val pinyinDict: Map<String, List<String>>
    init { pinyinDict = buildPinyinDict() }

    fun search(code: String): List<String> {
        if (code.isBlank()) return emptyList()
        val lc = code.lowercase()
        pinyinDict[lc]?.let { return it }
        val segs = segmentPinyin(lc)
        if (segs.isNotEmpty() && segs[0].size > 1) {
            val c = combineSegments(segs[0])
            if (c.isNotEmpty()) return c
        }
        val pm = pinyinDict.filterKeys { it.startsWith(lc) && it != lc }.flatMap { it.value }.distinct()
        if (pm.isNotEmpty()) return pm.take(20)
        return emptyList()
    }

    fun searchFuzzy(code: String): List<String> {
        if (code.isBlank()) return emptyList()
        val lc = code.lowercase()
        val ex = search(lc)
        if (ex.isNotEmpty()) return ex
        val variants = generateFuzzyVariants(lc)
        val results = mutableSetOf<String>()
        for (v in variants) { results.addAll(search(v)) }
        return results.toList()
    }

    fun segmentPinyin(input: String): List<List<String>> {
        if (input.isBlank()) return emptyList()
        val r = mutableListOf<List<String>>()
        segDfs(input.lowercase(), 0, mutableListOf(), r)
        return r.sortedBy { it.size }
    }

    private fun segDfs(inp: String, pos: Int, cur: MutableList<String>, res: MutableList<List<String>>) {
        if (pos == inp.length) { res.add(cur.toList()); return }
        val ml = minOf(6, inp.length - pos)
        for (len in ml downTo 1) {
            val s = inp.substring(pos, pos + len)
            if (s in VALID_SYLLABLES) { cur.add(s); segDfs(inp, pos + len, cur, res); cur.removeAt(cur.size - 1) }
        }
    }

    private fun generateFuzzyVariants(code: String): List<String> {
        val v = mutableListOf(code)
        for ((from, to) in FUZZY_PAIRS) { if (code.contains(from)) v.add(code.replace(from, to)) }
        val c = mutableListOf<String>()
        for (vv in v) for ((from, to) in FUZZY_PAIRS) { if (vv.contains(from)) c.add(vv.replace(from, to)) }
        v.addAll(c)
        return v.distinct()
    }

    private fun combineSegments(segs: List<String>): List<String> {
        if (segs.isEmpty()) return emptyList()
        if (segs.size == 2) { pinyinDict[segs[0]+segs[1]]?.let { return it } }
        if (segs.size == 3) { pinyinDict[segs[0]+segs[1]+segs[2]]?.let { return it } }
        val cps = segs.map { pinyinDict[it] ?: listOf(it) }
        val r = mutableListOf<String>()
        val fc = cps.map { it.firstOrNull() ?: "" }
        if (fc.all { it.isNotEmpty() }) r.add(fc.joinToString(""))
        return r.distinct()
    }

    fun getAbbreviation(code: String): String {
        val s = segmentPinyin(code)
        if (s.isEmpty()) return code
        return s[0].map { it.first() }.joinToString("")
    }

    private fun buildPinyinDict(): Map<String, List<String>> {
        return buildMap {
            fun a(p: String, chars: String) { put(p, chars.map { it.toString() }) }
'''
            # Add dictionary entries
            for py, chars in dict_entries:
                lines.append(f'            a("{py}","{chars}")')
            lines.append('''
        }
    }
}
''')

with open(out, 'w', encoding='utf-8') as f:
    for line in lines:
        f.write(line + '\n')
print(f"Wrote PinyinEngine.kt with {len(dict_entries)} entries")